(function () {
  'use strict';
  const D=CS_DATA,E=CS_ENGINE,KEY='cs-student-life.save.v1',COLLECTION='cs-student-life.achievements.v1';
  const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths={book:'M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4z M20 4h-4a3 3 0 0 0-3 3 M20 4v15h-3a4 4 0 0 0-4 2',code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',terminal:'m4 6 6 6-6 6m9 0h7',box:'m12 3 9 5v9l-9 5-9-5V8zm-9 5 9 5 9-5m-9 5v9m-5-17 10 5',flask:'M9 3h6m-5 0v7l-6 9a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3l-6-9V3M7 16h10',trophy:'M8 3h8v6a4 4 0 0 1-8 0zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 1v6m-4 2h8',briefcase:'M4 7h16v14H4z M8 7V3h8v4M4 12a20 20 0 0 0 16 0m-8 0v4',file:'M5 2h9l5 5v15H5zm9 0v6h5M8 12h8m-8 4h6',users:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3m17 0v-3a4 4 0 0 0-3-4M12 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0m4-3a3 3 0 0 1 0 6',heart:'M20 5c-3-3-6 0-8 2-2-2-5-5-8-2s0 7 8 14c8-7 11-11 8-14z',coffee:'M4 8h12v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm12 1h2a3 3 0 0 1 0 6h-2M7 2v2m5-2v2M2 22h18',wallet:'M4 5h15v16H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h13v2m2 6h-6v5h6m-4-2h1',branch:'M6 5v14m0-9c8 0 12 0 12-5M4 3h4v4H4zm12-2h4v4h-4zM4 17h4v4H4z',cap:'m2 8 10-5 10 5-10 5zm4 3v6c4 3 8 3 12 0v-6m4-3v8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',upload:'M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 4h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',refresh:'M20 7a8 8 0 1 0 0 10m0-14v5h-5',arrow:'M3 12h18m-6-6 6 6-6 6',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z'};
  const icon=n=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[n]||paths.code}"/></svg>`;
  const yuan=n=>'¥'+n.toLocaleString('zh-CN');
  let state=null,filter='常用',saveOK=true,collection=[],toastTimer;
  try{collection=JSON.parse(localStorage.getItem(COLLECTION)||'[]');if(!Array.isArray(collection))collection=[];collection=collection.filter(id=>D.achievements.some(a=>a.id===id));}catch{collection=[];}
  let loadError='';
  try {const saved=localStorage.getItem(KEY);if(saved)state=E.validate(JSON.parse(saved).state);}catch{loadError='原存档无法读取。可以导入之前导出的存档，或开启新人生。';}
  const isNew=!state; if(!state)state=E.create({name:'新同学',talents:['logic','healthy']});
  function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
  function save(){
    try{localStorage.setItem(KEY,JSON.stringify({format:'CS-LIFE',savedAt:new Date().toISOString(),state}));collection=[...new Set([...collection,...state.achievements])];localStorage.setItem(COLLECTION,JSON.stringify(collection));saveOK=true;}
    catch{saveOK=false;toast('浏览器暂时无法保存，请使用「存档」导出进度。');}
  }
  function bar(label,value,color=''){return `<div class="stat-label"><span>${label}</span><strong>${value}<span style="color:#a9b29e"> / 100</span></strong></div><div class="bar" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><div class="bar-fill ${value<20?'danger':color}" style="width:${value}%"></div></div>`;}
  function render(){
    const t=D.terms[state.semester-1],year=['大一','大二','大三','大四'][Math.floor((state.semester-1)/2)],term=state.semester%2?'上学期':'下学期';
    const count=state.plan.length,finished=state.phase==='ending';
    const choices=D.actions.filter(a=>filter==='常用'?['course','code','algorithm','project','exercise','rest'].includes(a.id):a.category===filter);
    const goals=[{name:'跟上本学期的课程',detail:`课程掌握 ${state.study} / 60`,done:state.study>=60},state.semester<3?{name:'编程达到 25',detail:`当前编程 ${state.code}`,done:state.code>=25}:state.semester<7?{name:'完成一个拿得出手的项目',detail:`累计项目 ${state.projects} 个`,done:state.projects>=1}:{name:'完成毕业设计',detail:`当前进度 ${state.thesis}%`,done:state.thesis>=100},{name:'给生活留一点空间',detail:'健康、心态均保持 60 以上',done:state.health>=60&&state.mood>=60}];
    $('#app').innerHTML=`<header><div class="brand"><div class="brand-mark">&gt;_</div><div><div class="brand-title">计算机学生模拟人生 <span>CS LIFE</span></div><div class="brand-sub">YOUR LIFE, YOUR SOURCE CODE.</div></div></div><div class="header-actions"><span class="save-status"><i class="status-dot"></i>${saveOK?'进度保存在此浏览器':'存档未保存，请导出'}</span><button class="quiet-btn" data-command="help" aria-label="玩法说明">${icon('help')}<span class="desktop-text">玩法</span></button><button class="quiet-btn" data-command="saves" aria-label="存档管理">${icon('download')}<span class="desktop-text">存档</span></button><button class="quiet-btn" data-command="new" aria-label="开启新人生">${icon('refresh')}<span class="desktop-text">重开</span></button></div></header>
      <main class="layout"><aside class="left-column"><section class="panel profile"><div class="eyebrow">STUDENT PROFILE / 学生档案</div><div class="profile-top"><div class="avatar">:)</div><div><div class="profile-name">${esc(state.name)}</div><div class="profile-role">计算机科学与技术 · ${year}</div></div></div><div class="tags">${state.talents.map(id=>`<span class="tag">${esc(D.talents.find(t=>t.id===id).name)}</span>`).join('')}<span class="tag">${esc(D.backgrounds.find(b=>b.id===state.background).name)}</span></div><div class="divider"></div><div>${bar('健康',state.health)}</div><div>${bar('心态',state.mood,'orange')}</div><div class="money-row"><span>生活费</span><strong>${yuan(state.money)}</strong></div><div class="ability"><h3>能力成长</h3>${bar('编程能力',state.code)}${bar('理论基础',state.theory,'blue')}${bar('算法思维',state.algorithm,'orange')}${bar('科研能力',state.research,'purple')}${bar('人脉连接',state.social)}</div></section><section class="gpa-card"><div class="eyebrow">CUMULATIVE GPA</div><div class="gpa-top"><div class="gpa">${state.grades.length?E.gpa(state).toFixed(2):'—'} <span>/ 4.00</span></div>${icon('cap')}</div><p>${state.grades.length?'累计绩点 · 每学期结算后更新':'第一份成绩单，会在期末到来。'}<br>已获 ${state.credits} 学分${state.failed?` · ${state.failed} 门待补考`:''}</p></section></aside>
      <section class="main-column"><div class="semester-label"><span class="chip">${year} · ${term}</span><span>${finished?'大学篇已结束':'第 '+state.semester+' / 8 学期'}</span></div><div class="term-top"><div><h1>${finished?'毕业快乐，下一站见。':t.name}</h1><p>${t.courses.join(' / ')}</p></div><div class="week-counter"><span class="eyebrow">WEEK </span><b>0${state.week}</b><span> / 04</span></div></div><div class="timeline" aria-label="第 ${state.semester} 学期，共八学期">${D.terms.map((_,i)=>`<span class="${i<state.semester-1?'done':i===state.semester-1?'current':''}"></span>`).join('')}</div>
      <section class="terminal"><div class="terminal-bar"><span class="terminal-dots"><i></i><i></i><i></i></span><span>campus / semester_${String(state.semester).padStart(2,'0')}</span><span>UTF-8</span></div><div class="terminal-content"><div><div class="terminal-code">$ ${finished?'git log --oneline':'./start_a_new_week.sh'}</div><h2>${finished?'四年，很长也很短。':state.week===1?'新的一页，由你来写。':['','', '生活不是一道单选题。','慢一点，也是在前进。','期末将至，别忘了自己。'][state.week]}</h2><p>${finished?'写过的代码会迭代，遇见的人和做过的选择，会留在你的人生里。':t.subtitle}</p></div><div class="pixel-computer" aria-hidden="true">&gt;_</div></div></section>
      <div class="mobile-summary"><span>健康 ${state.health}</span><span>心态 ${state.mood}</span><span>${yuan(state.money)}</span><span>GPA ${state.grades.length?E.gpa(state).toFixed(2):'—'}</span></div>
      ${finished?`<section class="end-card"><span class="eyebrow">${esc(state.ending.label)}</span><h2>${esc(state.ending.title)}</h2><p>${esc(state.ending.desc)}</p><button class="primary" data-command="ending">查看毕业档案 ${icon('arrow')}</button></section>`:`<div class="section-title"><h2>这周，想做些什么？</h2><small>每周 3 次行动 · 自己决定节奏</small></div><nav class="filters" aria-label="行动分类">${['常用','学习','成长','生活'].map(f=>`<button class="filter ${filter===f?'active':''}" aria-pressed="${filter===f}" data-filter="${f}">${f}</button>`).join('')}</nav><div class="action-grid">${choices.map(a=>{const reason=E.locked(state,a);return `<button class="action-card" data-category="${a.category}" data-action="${a.id}" ${reason||state.phase!=='planning'?'disabled':''} aria-label="${a.name}${reason?'，'+reason:''}"><div class="action-top"><span class="action-icon">${icon(a.icon)}</span><h3>${a.name}</h3><span class="plus">${reason?'·':'+'}</span></div><p class="action-description">${a.desc}</p><p class="action-effects">${a.hint}</p>${reason?`<div class="locked-note">${reason}</div>`:''}</button>`;}).join('')}</div><section class="plan"><div class="plan-title">本周计划<span>${count} / 3 SLOTS</span></div><div class="plan-slots">${Array.from({length:3},(_,i)=>state.plan[i]?`<button class="plan-slot filled" data-remove="${i}" aria-label="移除${D.actions.find(a=>a.id===state.plan[i]).name}">${D.actions.find(a=>a.id===state.plan[i]).name}<span>×</span></button>`:'<div class="plan-slot">＋ 空闲安排</div>').join('')}</div><button class="primary advance" data-command="advance" ${state.phase==='planning'&&count!==3?'disabled':''}><span>${state.phase==='event'?'回应本周的校园事件':state.phase==='report'?'查看本学期成绩单':'开始这一周'} <span aria-hidden="true">→</span></span><kbd>ENTER ↵</kbd></button><div class="plan-hint">${state.phase==='planning'?'点击上方行动加入计划 · 点击已选行动可移除':'请先完成本周事件与学期结算，再安排下一周'}</div></section>`}
      <div class="milestones"><span class="milestone">项目 <b>${state.projects}</b></span><span class="milestone">竞赛获奖 <b>${state.awards}</b></span><span class="milestone">科研成果 <b>${state.papers}</b></span><span class="milestone">实习 <b>${Math.floor(state.internSteps/2)}</b></span><span class="milestone">毕设 <b>${state.thesis}%</b></span></div></section>
      <aside class="right-column"><section class="panel goals"><div class="panel-heading"><h2>本学期的小目标</h2><span>${goals.filter(g=>g.done).length} / 3</span></div>${goals.map(g=>`<div class="goal-item"><span class="check ${g.done?'checked':''}">${g.done?'✓':''}</span><div>${g.name}<p>${g.detail}</p></div></div>`).join('')}<div class="goal-tip">${t.tip}</div>${state.projectProgress?`<div class="progress-project"><p>进行中的项目 · ${state.projectProgress}%</p><div class="bar"><div class="bar-fill" style="width:${state.projectProgress}%"></div></div></div>`:''}</section><section class="panel log-panel"><div class="panel-heading"><h2>校园手记</h2><span>LIFE.LOG</span></div><div class="log-list">${state.log.slice(0,35).map(l=>`<article class="log-item"><div class="log-time">S${String(l.semester).padStart(2,'0')} · W${String(l.week).padStart(2,'0')}${l.type==='achievement'?' · ACHIEVEMENT':''}</div><p class="log-text">${esc(l.text)}</p></article>`).join('')}</div></section><p class="footnote">这里没有标准答案。<br>绩点、代码、热爱和生活，都值得拥有自己的位置。</p></aside></main><footer class="footer"><span>CS LIFE v1.0 <span style="color:#b9c2ae">/</span> 人生不是程序，不必一次编译通过。</span><button data-command="achievements">${icon('star')} 成就 ${collection.length} / ${D.achievements.length}</button></footer>`;
  }
  function modal(html){const d=$('#modal');d.innerHTML=`<div class="modal-inner">${html}</div>`;if(!d.open)d.showModal();d.scrollTop=0;}
  function modalTop(label){return `<div class="modal-top"><span class="eyebrow">${label}</span><button class="close-btn" data-command="close" aria-label="关闭">×</button></div>`;}
  function close(){$('#modal').close();}
  function newGame(){
    modal(`${modalTop('NEW GAME / 入学登记')}<h2 id="modal-title">你好，未来的计算机人。</h2><p class="modal-lead">八个学期，三十二个关键周。<br>这一次，由你决定自己的大学生活。</p>${loadError?`<div class="notice">${esc(loadError)}</div>`:''}<form id="character-form"><label class="field-label" for="student-name">同学，怎么称呼你？</label><input class="name-input" id="student-name" name="name" maxlength="16" placeholder="输入你的名字" value="${isNew&&state.weeksPlayed===0?'':esc(state.name)}" autocomplete="off"><div class="field-label">你的起点</div><div class="option-grid">${D.backgrounds.map((b,i)=>`<label class="option"><input type="radio" name="background" value="${b.id}" ${i===0?'checked':''}><strong>${b.name}</strong><p>${b.desc}</p></label>`).join('')}</div><div class="field-label">带上两项天赋 <span style="font-weight:400;color:var(--muted)">· 选择 2 项</span></div><div class="talent-grid">${D.talents.map(t=>`<label class="talent"><input type="checkbox" name="talent" value="${t.id}" ${['logic','healthy'].includes(t.id)?'checked':''}><strong>${icon(t.icon)} ${t.name}</strong><p>${t.desc}</p></label>`).join('')}</div><div id="form-error" class="error-text" role="alert"></div>${state.weeksPlayed>0?'<p class="plan-hint">开始后将替换当前进度。已解锁成就会保留，可先关闭此窗口导出存档。</p>':''}<div class="modal-bottom"><button class="primary" type="submit">领取录取通知书 ${icon('arrow')}</button></div></form><p class="welcome-footer">NO PERFECT BUILD. JUST YOUR OWN STORY.</p>`);
    $('#character-form').addEventListener('change',e=>{if(e.target.name==='talent'&&document.querySelectorAll('[name=talent]:checked').length>2){e.target.checked=false;$('#form-error').textContent='最多选择两项天赋，先取消一项即可更换。';}else $('#form-error').textContent='';});
    $('#character-form').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target),talents=form.getAll('talent');if(talents.length!==2){$('#form-error').textContent='请选择两项天赋。';return;}state=E.create({name:form.get('name'),background:form.get('background'),talents});loadError='';filter='常用';save();close();render();toast('入学成功。安排你的第一周吧！');});
  }
  function showPhase(){
    if(state.phase==='event') {
      const ev=D.events.find(e=>e.id===state.pendingEvent);
      modal(`${modalTop('CAMPUS ENCOUNTER / 校园事件')}<div class="event-art"><span>SEMESTER ${String(state.semester).padStart(2,'0')} / WEEK 0${state.week}</span>${icon(ev.icon)}</div><h2 id="modal-title">${ev.title}</h2><p class="modal-lead">${ev.body}</p>${ev.choices.map((c,i)=>`<button class="choice" data-choice="${i}" ${state.money+(c.effects.money||0)<0?'disabled':''}><strong>${c.text}</strong><p>${E.effectsText(c.effects)}${state.money+(c.effects.money||0)<0?' · 生活费不足':''}</p></button>`).join('')}`);
    } else if(state.phase==='report') {
      const r=state.report;
      modal(`${modalTop('SEMESTER REPORT / 学期结算')}<h2 id="modal-title">第 ${r.semester} 学期，辛苦了。</h2><p class="modal-lead">${r.gpa>=3.6?'这份成绩单，记得奖励一下自己。':r.passed?'又走完一段路。知识在积累，你也在慢慢成长。':'有一门课需要补考。调整节奏，下一学期还来得及。'}</p><div class="results-grid"><div class="result-cell"><b>${r.gpa.toFixed(2)}</b><span>本学期绩点</span></div><div class="result-cell"><b>+${r.credits}</b><span>本学期学分</span></div><div class="result-cell"><b>${yuan(r.scholarship)}</b><span>本学期奖学金</span></div></div><div class="report-line"><span>累计绩点</span><strong>${E.gpa(state).toFixed(2)} / 4.00</strong></div><div class="report-line"><span>已获学分 / 毕业最低要求</span><strong>${state.credits} / 152</strong></div><div class="report-line"><span>待补考课程</span><strong>${state.failed} 门</strong></div>${state.semester>=7?`<div class="report-line"><span>毕业设计</span><strong>${state.thesis}% / 100%</strong></div>`:''}<div class="modal-bottom"><button class="primary" data-command="continue">${state.semester===8?'打开我的毕业档案':'放个假，进入下一学期'} ${icon('arrow')}</button></div>`);
    } else if(state.phase==='ending') showEnding();
  }
  function showEnding(){const en=state.ending;if(!en)return;modal(`${modalTop('TO BE CONTINUED / 毕业档案')}<div class="ending-symbol">${icon(en.id==='delayed'?'refresh':'cap')}</div><span class="tag">${esc(en.label)}</span><h2 id="modal-title">${esc(en.title)}</h2><p class="modal-lead">${esc(state.name)}，${esc(en.desc)}</p><div class="results-grid"><div class="result-cell"><b>${E.gpa(state).toFixed(2)}</b><span>累计 GPA</span></div><div class="result-cell"><b>${state.projects}</b><span>完成项目</span></div><div class="result-cell"><b>${state.achievements.length}</b><span>本局成就</span></div></div><div class="ending-note">${esc(en.advice)}</div><div class="report-line"><span>竞赛获奖 / 科研成果 / 实习经历</span><strong>${state.awards} / ${state.papers} / ${Math.floor(state.internSteps/2)}</strong></div><div class="report-line"><span>健康 / 心态</span><strong>${state.health} / ${state.mood}</strong></div><div class="modal-bottom"><button class="quiet-btn" data-command="export">导出这段人生</button><button class="primary" data-command="new">再体验一种可能 ${icon('refresh')}</button></div>`);}
  function help(){modal(`${modalTop('PLAYER GUIDE / 新生手册')}<h2 id="modal-title">大学四年，怎么玩？</h2><div class="help-section"><h3>01 · 安排每一周</h3><p>选 3 项行动，点击「开始这一周」。同一项可重复选择，点击计划中的行动可以取消。行动会按计划顺序结算，随后发生一个有选择的校园事件。</p></div><div class="help-section"><h3>02 · 课程、能力和生活</h3><p>每学期有 4 个代表性的关键周，共 8 学期。上课提高本学期课程掌握，理论和编程也影响成绩。绩点达到 2.0 获得 20 学分，否则获得 12 学分并留下 1 门补考；下一学期「学习」页的补考可补回学分。平均绩点按已完成学期计算。</p></div><div class="help-section"><h3>03 · 找到自己的方向</h3><p>大二开放科研与竞赛，大三可以实习。项目和论文进度达到 100 后获得一项成果；每 2 次实习行动完成一段实习。竞赛获奖率随算法和人脉提高，上限 90%。</p></div><div class="help-section"><h3>04 · 毕业也要认真准备</h3><p>毕业需要至少 152 学分和 100% 毕业设计进度。大四「学习」页开启毕业设计。成绩、项目、科研、实习与人脉共同决定毕业结局，共 11 种可能。健康或心态低于 15 会触发休整，并产生最多 ¥150 支出。</p></div><div class="help-section"><h3>05 · 进度属于你</h3><p>每次操作后自动保存在当前浏览器。清理网站数据会删除存档；换设备或换网址前，请先导出。整个游戏离线可运行，不需要登录，也不会上传游戏数据。</p></div><div class="notice">本作是虚构的校园文字模拟。四个关键周是时间压缩，数值与结局不代表真实教育、招聘或人生评价。</div><button class="primary" data-command="close">明白，继续我的故事</button>`);}
  function saves(){modal(`${modalTop('SAVE FILE / 存档管理')}<h2 id="modal-title">给这段人生，留个备份。</h2><p class="modal-lead">进度仅保存在当前浏览器。导出的文件可以在另一台设备导入，继续同一段人生。</p><div class="report-line"><span>当前角色</span><strong>${esc(state.name)}</strong></div><div class="report-line"><span>当前进度</span><strong>第 ${state.semester} 学期 · 第 ${state.week} 周</strong></div><div class="modal-bottom"><button class="primary" data-command="export">${icon('download')} 导出存档</button><button class="quiet-btn" data-command="import">${icon('upload')} 导入存档</button></div><p class="plan-hint">导入前会检查文件；确认后才替换当前进度。</p>`);}
  function achievements(){modal(`${modalTop('ACHIEVEMENTS / 成就收藏')}<h2 id="modal-title">走过的路，都留下了痕迹。</h2><p class="modal-lead">已解锁 ${collection.length} / ${D.achievements.length}。成就会跨周目保留在此浏览器。</p><div class="achievement-grid">${D.achievements.map(a=>`<div class="achievement ${collection.includes(a.id)?'unlocked':''}">${icon(a.icon)}<strong>${a.name}</strong><p>${a.desc}</p></div>`).join('')}</div>`);}
  function exportSave(){const blob=new Blob([JSON.stringify({format:'CS-LIFE',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`CS-Life-S${state.semester}-W${state.week}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出，记得妥善保存。');}
  function mutate(fn){try{fn();save();render();return true;}catch(e){toast(e.message);return false;}}
  const commands={close,new:newGame,help,saves,achievements,ending:showEnding,export:exportSave,import:()=>$('#import-file').click(),advance:()=>{if(state.phase==='planning'){if(mutate(()=>E.advance(state)))showPhase();}else showPhase();},continue:()=>{if(mutate(()=>E.continueTerm(state))){close();if(state.phase==='ending')showPhase();else toast('假期结束，新学期开始了。');}}};
  document.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.command){commands[b.dataset.command]?.();return;}
    if(b.dataset.filter){filter=b.dataset.filter;render();document.querySelector(`[data-filter="${filter}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.action){const id=b.dataset.action;if(mutate(()=>E.addPlan(state,id))){toast(`${D.actions.find(a=>a.id===id).name}已加入计划（${state.plan.length}/3）`);document.querySelector(`[data-action="${id}"]`)?.focus({preventScroll:true});}return;}
    if(b.dataset.remove!==undefined){mutate(()=>E.removePlan(state,Number(b.dataset.remove)));return;}
    if(b.dataset.choice!==undefined){if(mutate(()=>E.choose(state,Number(b.dataset.choice)))){close();showPhase();}return;}
  });
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('#modal').open&&!['INPUT','TEXTAREA','BUTTON','SELECT'].includes(document.activeElement.tagName)&&state.phase==='planning'&&state.plan.length===3){e.preventDefault();commands.advance();}});
  $('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>300000)throw Error('存档文件过大，请选择本游戏导出的 JSON 文件');const raw=JSON.parse(await f.text());if(raw.format!=='CS-LIFE')throw Error('这不是本游戏的存档');const incoming=E.validate(raw.state);modal(`${modalTop('IMPORT SAVE / 导入存档')}<h2 id="modal-title">继续 ${esc(incoming.name)} 的故事？</h2><p class="modal-lead">第 ${incoming.semester} 学期，第 ${incoming.week} 周。<br>确认后将替换当前进度，已解锁成就保留。</p><div class="modal-bottom"><button class="quiet-btn" data-command="close">取消</button><button class="primary" id="confirm-import">确认导入</button></div>`);$('#confirm-import').addEventListener('click',()=>{state=incoming;save();close();render();showPhase();toast('存档已导入。');},{once:true});}catch(error){toast('导入失败：'+error.message);}});
  render();if(isNew)newGame();else showPhase();
  const context=document.modelContext;
  if(context?.registerTool){
    const lifecycle=new AbortController();
    const definitions=[{name:'read_student_life',description:'读取当前大学模拟进度、状态和可选行动，不改变游戏。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({name:state.name,semester:state.semester,week:state.week,phase:state.phase,health:state.health,mood:state.mood,gpa:E.gpa(state),plan:[...state.plan],actions:D.actions.map(a=>({id:a.id,name:a.name,locked:E.locked(state,a)}))})},{name:'set_week_plan',description:'替换当前周的行动计划，最多三项。只安排，不结算这一周。',inputSchema:{type:'object',properties:{actions:{type:'array',items:{type:'string'},maxItems:3}},required:['actions'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Array.isArray(input.actions)||input.actions.length>3||input.actions.some(id=>typeof id!=='string'))throw Error('提供最多三个行动 ID');if(state.phase!=='planning')throw Error('请先处理当前事件');const next=E.clone(state);next.plan=[];for(const id of input.actions)E.addPlan(next,id);state=next;save();render();return{plan:[...state.plan],executed:false};}}];
    for(const def of definitions){try{Promise.resolve(context.registerTool(def,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
