(function () {
  'use strict';
  const D=CS_DATA,E=CS_ENGINE,KEY='cs-student-life.save.v1',COLLECTION='cs-student-life.achievements.v1';
  const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths={book:'M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4z M20 4h-4a3 3 0 0 0-3 3 M20 4v15h-3a4 4 0 0 0-4 2',code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',terminal:'m4 6 6 6-6 6m9 0h7',box:'m12 3 9 5v9l-9 5-9-5V8zm-9 5 9 5 9-5m-9 5v9m-5-17 10 5',flask:'M9 3h6m-5 0v7l-6 9a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3l-6-9V3M7 16h10',trophy:'M8 3h8v6a4 4 0 0 1-8 0zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 1v6m-4 2h8',briefcase:'M4 7h16v14H4z M8 7V3h8v4M4 12a20 20 0 0 0 16 0m-8 0v4',file:'M5 2h9l5 5v15H5zm9 0v6h5M8 12h8m-8 4h6',users:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3m17 0v-3a4 4 0 0 0-3-4M12 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0m4-3a3 3 0 0 1 0 6',heart:'M20 5c-3-3-6 0-8 2-2-2-5-5-8-2s0 7 8 14c8-7 11-11 8-14z',coffee:'M4 8h12v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm12 1h2a3 3 0 0 1 0 6h-2M7 2v2m5-2v2M2 22h18',wallet:'M4 5h15v16H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h13v2m2 6h-6v5h6m-4-2h1',branch:'M6 5v14m0-9c8 0 12 0 12-5M4 3h4v4H4zm12-2h4v4h-4zM4 17h4v4H4z',cap:'m2 8 10-5 10 5-10 5zm4 3v6c4 3 8 3 12 0v-6m4-3v8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',upload:'M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 4h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',refresh:'M20 7a8 8 0 1 0 0 10m0-14v5h-5',arrow:'M3 12h18m-6-6 6 6-6 6',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z'};
  const icon=n=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[n]||paths.code}"/></svg>`;
  const yuan=n=>'¥'+n.toLocaleString('zh-CN');
  const statNames={...E.labels,projects:'项目',internSteps:'实习经历'};
  const rarityNames={common:'常见',uncommon:'少见',rare:'稀有'};
  let state=null,filter='常用',saveOK=true,collection=[],toastTimer,startDraft=null;
  try{collection=JSON.parse(localStorage.getItem(COLLECTION)||'[]');if(!Array.isArray(collection))collection=[];collection=collection.filter(id=>D.achievements.some(a=>a.id===id));}catch{collection=[];}
  let loadError='';
  try {const saved=localStorage.getItem(KEY);if(saved)state=E.validate(JSON.parse(saved).state);}catch{loadError='原存档无法读取。可以导入之前导出的存档，或开启新人生。';}
  const isNew=!state; if(!state)state=E.create({name:'新同学',talents:['logic','healthy']});
  function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
  function save(){
    try{localStorage.setItem(KEY,JSON.stringify({format:'CS-LIFE',savedAt:new Date().toISOString(),state}));collection=[...new Set([...collection,...state.achievements])];localStorage.setItem(COLLECTION,JSON.stringify(collection));saveOK=true;}
    catch{saveOK=false;toast('浏览器暂时无法保存，请使用「存档」导出进度。');}
  }
  function bar(label,value,color=''){return `<div class="stat-label"><span>${label}</span><strong>${value}<span style="color:#a9b29e"> / 100</span></strong></div><div class="bar" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><div class="bar-fill ${value<20?'danger':color}" style="width:${value}%"></div></div>`;}
  function abilityBar(label,value,use,color=''){return `<div class="ability-stat">${bar(label,value,color)}<p class="ability-use">${use}</p></div>`;}
  function progressCard(label,value,target,detail,color='',targetLabel=''){
    const width=Math.min(100,Math.max(0,value/target*100));
    return `<div class="growth-item"><div class="growth-item-top"><span>${label}</span><strong>${value}<small> / ${targetLabel||target}</small></strong></div><div class="bar" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${target}" aria-valuenow="${Math.min(value,target)}"><div class="bar-fill ${color}" style="width:${width}%"></div></div><p>${detail}</p></div>`;
  }
  function growthProgress(){
    const forecast=E.semesterForecast(state),projectsLocked=E.locked(state,D.actions.find(a=>a.id==='project')),labLocked=E.locked(state,D.actions.find(a=>a.id==='lab')),internLocked=E.locked(state,D.actions.find(a=>a.id==='intern'));
    return `<section class="growth-panel" aria-label="学业与成长进度"><div class="panel-heading"><h2>学业与成长进度</h2><span>每一步都有积累</span></div><div class="growth-grid">${progressCard('本学期课程掌握',state.study,75,'理论每提高 20，上课额外 +1；下学期清零。','','建议 75')}${progressCard('个人项目',state.projectProgress,100,`累计完成 ${state.projects} 个 · ${projectsLocked?'编程达到 15 后开启':'编程越高，每次开发推进越多'}`,'blue')}${progressCard('科研论文',state.paperProgress,100,`累计成果 ${state.papers} 篇 · ${labLocked?'大二且理论达到 25 后开启':'科研达到 60 额外 +5；每 25 人脉额外 +2'}`,'purple')}${progressCard('当前实习阶段',state.internSteps%2,2,`已完成 ${Math.floor(state.internSteps/2)} 段 · ${internLocked?'大三、编程 40、完成 1 个项目后开启':'每完成 2 次实习行动，记为 1 段经历'}`,'orange')}${progressCard('毕业设计',state.thesis,100,state.semester<7?'大四开放，毕业时需要达到 100%。':'毕业需要完成 100%，同时取得至少 152 学分。')}<div class="growth-item forecast"><div class="growth-item-top"><span>预计本学期期末 GPA</span></div><strong class="forecast-value">${forecast.min.toFixed(2)}<span>–</span>${forecast.max.toFixed(2)}</strong><p>按当前状态估算，后续行动和随机波动会改变结果。</p><details><summary>看看成绩怎么算</summary><p>课程 +${forecast.course.toFixed(2)} · 理论 +${forecast.theory.toFixed(2)} · 编程 +${forecast.code.toFixed(2)}<br>基础项 ${forecast.base.toFixed(2)}（含学期难度）；最终绩点为 0–4。</p></details></div></div></section>`;
  }
  function recentGrowth(){
    const week=state.lastWeek;if(!week)return '';
    const changes=Object.entries(week.effects||{}).filter(([,value])=>value!==0);
    return `<section class="recent-growth"><div><h3>最近一周成长</h3><span>第 ${week.semester} 学期 · 第 ${week.week} 周，事件结果另行结算</span></div><div class="growth-chips">${changes.length?changes.map(([key,value])=>`<span class="growth-chip ${value<0?'loss':'gain'}">${esc(E.effectsText({[key]:value}))}</span>`).join(''):'<span class="growth-chip">本周无数值变化</span>'}</div></section>`;
  }
  function render(){
    const t=D.terms[state.semester-1],year=['大一','大二','大三','大四'][Math.floor((state.semester-1)/2)],term=state.semester%2?'上学期':'下学期';
    const count=state.plan.length,finished=state.phase==='ending';
    const choices=D.actions.filter(a=>filter==='常用'?['course','code','algorithm','project','exercise','rest'].includes(a.id):a.category===filter);
    const goals=[{name:'跟上本学期的课程',detail:`课程掌握 ${state.study} / 75`,done:state.study>=75},state.semester<3?{name:'编程达到 25',detail:`当前编程 ${state.code}`,done:state.code>=25}:state.semester<7?{name:'完成一个拿得出手的项目',detail:`累计项目 ${state.projects} 个`,done:state.projects>=1}:{name:'完成毕业设计',detail:`当前进度 ${state.thesis}%`,done:state.thesis>=100},{name:'给生活留一点空间',detail:'健康、心态均保持 60 以上',done:state.health>=60&&state.mood>=60}];
    $('#app').innerHTML=`<header><div class="brand"><div class="brand-mark">&gt;_</div><div><div class="brand-title">计算机学生模拟人生 <span>CS LIFE</span></div><div class="brand-sub">YOUR LIFE, YOUR SOURCE CODE.</div></div></div><div class="header-actions"><span class="save-status"><i class="status-dot"></i>${saveOK?'进度保存在此浏览器':'存档未保存，请导出'}</span><button class="quiet-btn" data-command="help" aria-label="玩法说明">${icon('help')}<span class="desktop-text">玩法</span></button><button class="quiet-btn" data-command="saves" aria-label="存档管理">${icon('download')}<span class="desktop-text">存档</span></button><button class="quiet-btn" data-command="new" aria-label="开启新人生">${icon('refresh')}<span class="desktop-text">重开</span></button></div></header>
      <main class="layout"><aside class="left-column"><section class="panel profile"><div class="eyebrow">STUDENT PROFILE / 学生档案</div><div class="profile-top"><div class="avatar">:)</div><div><div class="profile-name">${esc(state.name)}</div><div class="profile-role">计算机科学与技术 · ${year}</div></div></div><div class="tags">${state.talents.map(id=>`<span class="tag">${esc(D.talents.find(t=>t.id===id).name)}</span>`).join('')}<span class="tag">${esc(D.backgrounds.find(b=>b.id===state.background).name)}</span></div><div class="divider"></div><div>${bar('健康',state.health)}</div><div>${bar('心态',state.mood,'orange')}</div><div class="money-row"><span>生活费</span><strong>${yuan(state.money)}</strong></div><div class="ability"><h3>能力成长</h3>${abilityBar('编程能力',state.code,'开发项目 · 解锁实习')}${abilityBar('理论基础',state.theory,'上课效率 · 期末成绩 · 科研门槛','blue')}${abilityBar('算法思维',state.algorithm,'竞赛获奖 · 算法挑战','orange')}${abilityBar('科研能力',state.research,'论文推进 · 深造方向','purple')}${abilityBar('人脉关系',state.social,'沟通事件 · 科研协作 · 竞赛获奖')}</div></section><section class="gpa-card"><div class="eyebrow">CUMULATIVE GPA</div><div class="gpa-top"><div class="gpa">${state.grades.length?E.gpa(state).toFixed(2):'—'} <span>/ 4.00</span></div>${icon('cap')}</div><p>${state.grades.length?'累计绩点 · 每学期结算后更新':'第一份成绩单，会在期末到来。'}<br>已获 ${state.credits} 学分${state.failed?` · ${state.failed} 门待补考`:''}</p></section></aside>
      <section class="main-column"><div class="semester-label"><span class="chip">${year} · ${term}</span><span>${finished?'大学篇已结束':'第 '+state.semester+' / 8 学期'}</span></div><div class="term-top"><div><h1>${finished?'毕业快乐，下一站见。':t.name}</h1><p>${t.courses.join(' / ')}</p></div><div class="week-counter"><span class="eyebrow">WEEK </span><b>0${state.week}</b><span> / 04</span></div></div><div class="timeline" aria-label="第 ${state.semester} 学期，共八学期">${D.terms.map((_,i)=>`<span class="${i<state.semester-1?'done':i===state.semester-1?'current':''}"></span>`).join('')}</div>
      ${growthProgress()}${recentGrowth()}<div class="mobile-summary"><span>健康 ${state.health}</span><span>心态 ${state.mood}</span><span>${yuan(state.money)}</span><span>GPA ${state.grades.length?E.gpa(state).toFixed(2):'—'}</span></div>
      ${finished?`<section class="end-card"><span class="eyebrow">${esc(state.ending.label)}</span><h2>${esc(state.ending.title)}</h2><p>${esc(state.ending.desc)}</p><button class="primary" data-command="ending">查看毕业档案 ${icon('arrow')}</button></section>`:`<div class="section-title"><h2>这周，想做些什么？</h2><small>每周 3 次行动 · 自己决定节奏</small></div><nav class="filters" aria-label="行动分类">${['常用','学习','成长','生活'].map(f=>`<button class="filter ${filter===f?'active':''}" aria-pressed="${filter===f}" data-filter="${f}">${f}</button>`).join('')}</nav><div class="action-grid">${choices.map(a=>{const reason=E.locked(state,a);return `<button class="action-card" data-category="${a.category}" data-action="${a.id}" ${reason||state.phase!=='planning'?'disabled':''} aria-label="${a.name}${reason?'，'+reason:''}"><div class="action-top"><span class="action-icon">${icon(a.icon)}</span><h3>${a.name}</h3><span class="plus">${reason?'·':'+'}</span></div><p class="action-description">${a.desc}</p><p class="action-effects">${esc(E.effectsText(E.actionPreview(state,a.id)))}${a.id==='contest'?'<span class="random-note">获奖另行随机结算</span>':''}</p>${reason?`<div class="locked-note">${reason}</div>`:''}</button>`;}).join('')}</div><section class="plan"><div class="plan-title">本周计划<span>${count} / 3 SLOTS</span></div><div class="plan-slots">${Array.from({length:3},(_,i)=>state.plan[i]?`<button class="plan-slot filled" data-remove="${i}" aria-label="移除${D.actions.find(a=>a.id===state.plan[i]).name}">${D.actions.find(a=>a.id===state.plan[i]).name}<span>×</span></button>`:'<div class="plan-slot">＋ 空闲安排</div>').join('')}</div><button class="primary advance" data-command="advance" ${state.phase==='planning'&&count!==3?'disabled':''}><span>${state.phase==='event'?'回应本周的校园事件':state.phase==='report'?'查看本学期成绩单':'开始这一周'} <span aria-hidden="true">→</span></span><kbd>ENTER ↵</kbd></button><div class="plan-hint">${state.phase==='planning'?'行动收益按当前属性预估，依计划顺序结算 · 点击已选行动可移除':'请先完成本周事件与学期结算，再安排下一周'}</div></section>`}
      <div class="milestones"><span class="milestone">项目 <b>${state.projects}</b></span><span class="milestone">竞赛获奖 <b>${state.awards}</b></span><span class="milestone">科研成果 <b>${state.papers}</b></span><span class="milestone">实习 <b>${Math.floor(state.internSteps/2)}</b></span><span class="milestone">毕设 <b>${state.thesis}%</b></span></div></section>
      <aside class="right-column"><section class="panel goals"><div class="panel-heading"><h2>本学期的小目标</h2><span>${goals.filter(g=>g.done).length} / 3</span></div>${goals.map(g=>`<div class="goal-item"><span class="check ${g.done?'checked':''}">${g.done?'✓':''}</span><div>${g.name}<p>${g.detail}</p></div></div>`).join('')}<div class="goal-tip">${t.tip}</div>${state.projectProgress?`<div class="progress-project"><p>进行中的项目 · ${state.projectProgress}%</p><div class="bar"><div class="bar-fill" style="width:${state.projectProgress}%"></div></div></div>`:''}</section><section class="panel log-panel"><div class="panel-heading"><h2>校园手记</h2><span>LIFE.LOG</span></div><div class="log-list">${state.log.slice(0,35).map(l=>`<article class="log-item"><div class="log-time">S${String(l.semester).padStart(2,'0')} · W${String(l.week).padStart(2,'0')}${l.type==='achievement'?' · ACHIEVEMENT':''}</div><p class="log-text">${esc(l.text)}</p></article>`).join('')}</div></section><p class="footnote">这里没有标准答案。<br>绩点、代码、热爱和生活，都值得拥有自己的位置。</p></aside></main><footer class="footer"><span>CS LIFE v1.1 <span style="color:#b9c2ae">/</span> 人生不是程序，不必一次编译通过。</span><button data-command="achievements">${icon('star')} 成就 ${collection.length} / ${D.achievements.length}</button></footer>`;
  }
  function modal(html){const d=$('#modal');d.dataset.resultOpen='false';d.innerHTML=`<div class="modal-inner">${html}</div>`;if(!d.open)d.showModal();d.scrollTop=0;}
  function modalTop(label){return `<div class="modal-top"><span class="eyebrow">${label}</span><button class="close-btn" data-command="close" aria-label="关闭">×</button></div>`;}
  function close(){$('#modal').close();}
  function freshSeed(){const values=new Uint32Array(1);if(globalThis.crypto?.getRandomValues){globalThis.crypto.getRandomValues(values);return values[0]||1;}return (Date.now()^Math.floor(Math.random()*4294967296))>>>0||1;}
  function newGame(){
    const seed=freshSeed();
    startDraft={name:isNew&&state.weeksPlayed===0?'':state.name,background:D.backgrounds[0].id,seed,pool:E.drawTalents(seed,8),rerolls:2};
    showCharacterForm();
  }
  function showCharacterForm(){
    const draft=startDraft;
    modal(`${modalTop('NEW GAME / 入学登记')}<h2 id="modal-title">你好，未来的计算机人。</h2><p class="modal-lead">八个学期，三十二个关键周。<br>这一次，由你决定自己的大学生活。</p>${loadError?`<div class="notice">${esc(loadError)}</div>`:''}<form id="character-form"><label class="field-label" for="student-name">同学，怎么称呼你？</label><input class="name-input" id="student-name" name="name" maxlength="16" placeholder="输入你的名字" value="${esc(draft.name)}" autocomplete="off"><div class="field-label">你的起点</div><div class="option-grid">${D.backgrounds.map(b=>`<label class="option"><input type="radio" name="background" value="${b.id}" ${b.id===draft.background?'checked':''}><strong>${b.name}</strong><p>${b.desc}</p></label>`).join('')}</div><div class="talent-heading"><div><div class="field-label">带上两项天赋 <span id="talent-count" role="status" aria-live="polite">已选 0 / 2</span></div><p>从 ${D.talents.length} 项天赋中随机遇见 8 项，每次入学都有新可能。</p></div><button class="quiet-btn reroll-btn" type="button" id="reroll-talents" ${draft.rerolls===0?'disabled':''}>${icon('refresh')}<span>重抽天赋<small>剩余 ${draft.rerolls} 次</small></span></button></div><div class="talent-grid">${draft.pool.map(id=>D.talents.find(t=>t.id===id)).map(t=>`<label class="talent" data-rarity="${esc(t.rarity||'common')}"><input type="checkbox" name="talent" value="${t.id}"><span class="talent-top"><strong>${icon(t.icon)} ${esc(t.name)}</strong><span class="rarity rarity-${esc(t.rarity||'common')}">${rarityNames[t.rarity]||rarityNames.common}</span></span><p>${esc(t.desc)}</p></label>`).join('')}</div><div id="form-error" class="error-text" role="alert"></div>${state.weeksPlayed>0?'<p class="plan-hint">开始后将替换当前进度。已解锁成就会保留，可先关闭此窗口导出存档。</p>':''}<div class="modal-bottom"><button class="primary" type="submit">领取录取通知书 ${icon('arrow')}</button></div></form><p class="welcome-footer">NO PERFECT BUILD. JUST YOUR OWN STORY.</p>`);
    const form=$('#character-form');
    form.addEventListener('change',e=>{
      if(e.target.name==='talent'&&form.querySelectorAll('[name=talent]:checked').length>2){e.target.checked=false;$('#form-error').textContent='最多选择两项天赋，先取消一项即可更换。';}
      else $('#form-error').textContent='';
      $('#talent-count').textContent=`已选 ${form.querySelectorAll('[name=talent]:checked').length} / 2`;
    });
    $('#reroll-talents').addEventListener('click',()=>{
      if(draft.rerolls<=0)return;
      const values=new FormData(form);draft.name=values.get('name');draft.background=values.get('background');draft.seed=freshSeed();draft.pool=E.drawTalents(draft.seed,8);draft.rerolls--;
      showCharacterForm();(draft.rerolls?$('#reroll-talents'):$('#character-form [name=talent]')).focus({preventScroll:true});toast('已遇见一组新天赋，请重新选择两项。');
    });
    form.addEventListener('submit',e=>{e.preventDefault();const values=new FormData(form),talents=values.getAll('talent');if(talents.length!==2||talents.some(id=>!draft.pool.includes(id))){$('#form-error').textContent='请从本次抽到的天赋中选择两项。';return;}state=E.create({name:values.get('name'),background:values.get('background'),talents,seed:draft.seed});startDraft=null;loadError='';filter='常用';save();close();render();toast('入学成功。安排你的第一周吧！');});
  }
  function eventContext(ev){
    const requirements=(ev.requires||[]).map(r=>`${statNames[r.stat]||r.stat}${r.min!==undefined?' ≥ '+r.min:''}${r.max!==undefined?' ≤ '+r.max:''}（当前 ${state[r.stat]}）`);
    const tendencies=(ev.bias||[]).map(b=>`${statNames[b.stat]||b.stat}越${b.direction==='low'?'低':'高'}，越容易遇到`);
    return `<div class="event-context"><strong>校园中的随机相遇</strong><p>${requirements.length?'出现条件：'+esc(requirements.join(' · '))+'<br>':''}${tendencies.length?esc(tendencies.join('；'))+'。':'事件会在本学期符合条件的遭遇中随机出现。'}</p></div>`;
  }
  function eventChoice(c,i){
    const reason=E.choiceError(state,c),check=c.check;
    const details=check?`<p class="choice-check"><span>${esc(statNames[check.stat]||check.stat)}检定 · 当前 ${state[check.stat]} · 难度 ${check.difficulty}</span><strong>成功率 ${Math.round(E.checkChance(state,check)*100)}%</strong></p>${Object.keys(c.effects||{}).length?`<p class="choice-fixed">固定变化（无论成败）：${esc(E.effectsText(c.effects||{}))}</p>`:''}<div class="choice-outcomes"><p><span class="outcome-label success">成功</span>${esc(E.effectsText(check.success.effects||{})||'无数值变化')}</p><p><span class="outcome-label failure">未达成</span>${esc(E.effectsText(check.failure.effects||{})||'无数值变化')}</p></div>`:`<p>${esc(E.effectsText(c.effects||{})||'无数值变化')}</p>`;
    return `<button class="choice" data-choice="${i}" ${reason?'disabled':''}><strong>${esc(c.text)}</strong>${details}${reason?`<p class="choice-lock">${esc(reason)}</p>`:''}</button>`;
  }
  function showEventResult(){
    const result=state.lastEvent;
    if(!result){close();showPhase();return;}
    const title={success:'挑战成功',failure:'这次未能达成',normal:'校园日常'}[result.outcome]||'事件结果';
    const changes=E.effectsText(result.effects)||'没有数值变化';
    modal(`<div class="modal-top"><span class="eyebrow">EVENT RESULT / 事件结果</span><span class="outcome-badge ${esc(result.outcome)}">${title}</span></div><h2 id="modal-title">${esc(result.title)}</h2><p class="modal-lead">${esc(result.result)}</p><div class="event-result"><span>本次实际变化</span><p>${esc(changes)}</p></div>${result.chance!==null&&result.chance!==undefined?`<p class="result-chance">本次成功率 ${Math.round(result.chance*100)}% · 属性影响概率，每次挑战仍有不同可能。</p>`:''}<div class="modal-bottom"><button class="primary" data-command="event-continue">继续 ${icon('arrow')}</button></div>`);
    $('#modal').dataset.resultOpen='true';$('#modal [data-command="event-continue"]').focus({preventScroll:true});
  }
  function showPhase(){
    if(state.phase==='event') {
      const ev=D.events.find(e=>e.id===state.pendingEvent);
      modal(`${modalTop('CAMPUS ENCOUNTER / 校园事件')}<div class="event-art"><span>SEMESTER ${String(state.semester).padStart(2,'0')} / WEEK 0${state.week}</span>${icon(ev.icon)}</div><h2 id="modal-title">${esc(ev.title)}</h2><p class="modal-lead">${esc(ev.body)}</p>${eventContext(ev)}${ev.choices.map(eventChoice).join('')}`);
    } else if(state.phase==='report') {
      const r=state.report;
      modal(`${modalTop('SEMESTER REPORT / 学期结算')}<h2 id="modal-title">第 ${r.semester} 学期，辛苦了。</h2><p class="modal-lead">${r.gpa>=3.6?'这份成绩单，记得奖励一下自己。':r.passed?'又走完一段路。知识在积累，你也在慢慢成长。':'有一门课需要补考。调整节奏，下一学期还来得及。'}</p><div class="results-grid"><div class="result-cell"><b>${r.gpa.toFixed(2)}</b><span>本学期绩点</span></div><div class="result-cell"><b>+${r.credits}</b><span>本学期学分</span></div><div class="result-cell"><b>${yuan(r.scholarship)}</b><span>本学期奖学金</span></div></div><div class="report-line"><span>累计绩点</span><strong>${E.gpa(state).toFixed(2)} / 4.00</strong></div><div class="report-line"><span>已获学分 / 毕业最低要求</span><strong>${state.credits} / 152</strong></div><div class="report-line"><span>待补考课程</span><strong>${state.failed} 门</strong></div>${state.semester>=7?`<div class="report-line"><span>毕业设计</span><strong>${state.thesis}% / 100%</strong></div>`:''}<div class="modal-bottom"><button class="primary" data-command="continue">${state.semester===8?'打开我的毕业档案':'放个假，进入下一学期'} ${icon('arrow')}</button></div>`);
    } else if(state.phase==='ending') showEnding();
  }
  function showEnding(){const en=state.ending;if(!en)return;modal(`${modalTop('TO BE CONTINUED / 毕业档案')}<div class="ending-symbol">${icon(en.id==='delayed'?'refresh':'cap')}</div><span class="tag">${esc(en.label)}</span><h2 id="modal-title">${esc(en.title)}</h2><p class="modal-lead">${esc(state.name)}，${esc(en.desc)}</p><div class="results-grid"><div class="result-cell"><b>${E.gpa(state).toFixed(2)}</b><span>累计 GPA</span></div><div class="result-cell"><b>${state.projects}</b><span>完成项目</span></div><div class="result-cell"><b>${state.achievements.length}</b><span>本局成就</span></div></div><div class="ending-note">${esc(en.advice)}</div><div class="report-line"><span>竞赛获奖 / 科研成果 / 实习经历</span><strong>${state.awards} / ${state.papers} / ${Math.floor(state.internSteps/2)}</strong></div><div class="report-line"><span>健康 / 心态</span><strong>${state.health} / ${state.mood}</strong></div><div class="modal-bottom"><button class="quiet-btn" data-command="export">导出这段人生</button><button class="primary" data-command="new">再体验一种可能 ${icon('refresh')}</button></div>`);}
  function help(){modal(`${modalTop('PLAYER GUIDE / 新生手册')}<h2 id="modal-title">大学四年，怎么玩？</h2><div class="help-section"><h3>01 · 遇见不同的自己</h3><p>每次新人生从 ${D.talents.length} 项天赋中随机抽取 8 项，由你选择 2 项带入大学。常见、少见和稀有天赋的出现概率不同。开局有 2 次重抽机会，重抽会清空天赋选择，并保留已填写的名字和家庭背景。</p></div><div class="help-section"><h3>02 · 安排每一周</h3><p>选 3 项行动，点击「开始这一周」。同一项可重复选择，点击计划中的行动可以取消。行动按计划顺序结算，随后随机遇见校园事件。事件会根据学期、属性和经历筛选，属性也会改变某些事件出现的机会。带有属性检定的选项会展示当前能力、成功率及不同后果；能力越强，成功机会通常越大，但仍有随机性。选择后会显示实际结果和属性变化。</p></div><div class="help-section"><h3>03 · 课程、能力和生活</h3><p>每学期有 4 个代表性的关键周，共 8 学期。课程掌握是本学期的学习进度，下学期清零；理论基础会长期保留。每次上课增加 15 + 理论每满 20 点额外增加 1 点课程掌握，再叠加天赋加成。课程、理论和编程共同影响成绩，可在「预计期末 GPA」展开查看当前贡献。绩点达到 2.0 获得 20 学分，否则获得 12 学分并留下 1 门补考；下一学期「学习」页的补考可补回学分。平均绩点按已完成学期计算。</p></div><div class="help-section"><h3>04 · 找到自己的方向</h3><p>大二开放科研与竞赛，大三可以实习。项目和论文进度达到 100 后获得一项成果；每 2 次实习行动完成一段实习。科研能力达到 60 后，每次实验室行动额外推进 5 点论文；人脉每满 25 点，再额外推进 2 点论文。每点人脉也提高 0.1 个百分点的竞赛获奖率，竞赛最终成功率上限 90%。人脉还会影响沟通检定和相关随机事件。</p></div><div class="help-section"><h3>05 · 毕业也要认真准备</h3><p>毕业需要至少 152 学分和 100% 毕业设计进度。大四「学习」页开启毕业设计。成绩、项目、科研、实习与人脉共同决定毕业结局，共 11 种可能。健康或心态低于 15 会触发休整，并产生最多 ¥150 支出。</p></div><div class="help-section"><h3>06 · 进度属于你</h3><p>每次操作后自动保存在当前浏览器。清理网站数据会删除存档；换设备或换网址前，请先导出。已有角色保留原来的天赋，新开人生才会重新抽取。整个游戏离线可运行，不需要登录，也不会上传游戏数据。</p></div><div class="notice">本作是虚构的校园文字模拟。四个关键周是时间压缩，数值与结局不代表真实教育、招聘或人生评价。</div><button class="primary" data-command="close">明白，继续我的故事</button>`);}
  function saves(){modal(`${modalTop('SAVE FILE / 存档管理')}<h2 id="modal-title">给这段人生，留个备份。</h2><p class="modal-lead">进度仅保存在当前浏览器。导出的文件可以在另一台设备导入，继续同一段人生。</p><div class="report-line"><span>当前角色</span><strong>${esc(state.name)}</strong></div><div class="report-line"><span>当前进度</span><strong>第 ${state.semester} 学期 · 第 ${state.week} 周</strong></div><div class="modal-bottom"><button class="primary" data-command="export">${icon('download')} 导出存档</button><button class="quiet-btn" data-command="import">${icon('upload')} 导入存档</button></div><p class="plan-hint">导入前会检查文件；确认后才替换当前进度。</p>`);}
  function achievements(){modal(`${modalTop('ACHIEVEMENTS / 成就收藏')}<h2 id="modal-title">走过的路，都留下了痕迹。</h2><p class="modal-lead">已解锁 ${collection.length} / ${D.achievements.length}。成就会跨周目保留在此浏览器。</p><div class="achievement-grid">${D.achievements.map(a=>`<div class="achievement ${collection.includes(a.id)?'unlocked':''}">${icon(a.icon)}<strong>${a.name}</strong><p>${a.desc}</p></div>`).join('')}</div>`);}
  function exportSave(){const blob=new Blob([JSON.stringify({format:'CS-LIFE',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`CS-Life-S${state.semester}-W${state.week}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出，记得妥善保存。');}
  function mutate(fn){try{fn();save();render();return true;}catch(e){toast(e.message);return false;}}
  const commands={close,new:newGame,help,saves,achievements,ending:showEnding,export:exportSave,import:()=>$('#import-file').click(),'event-continue':()=>{close();showPhase();},advance:()=>{if(state.phase==='planning'){if(mutate(()=>E.advance(state)))showPhase();}else showPhase();},continue:()=>{if(mutate(()=>E.continueTerm(state))){close();if(state.phase==='ending')showPhase();else toast('假期结束，新学期开始了。');}}};
  document.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.command){commands[b.dataset.command]?.();return;}
    if(b.dataset.filter){filter=b.dataset.filter;render();document.querySelector(`[data-filter="${filter}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.action){const id=b.dataset.action;if(mutate(()=>E.addPlan(state,id))){toast(`${D.actions.find(a=>a.id===id).name}已加入计划（${state.plan.length}/3）`);document.querySelector(`[data-action="${id}"]`)?.focus({preventScroll:true});}return;}
    if(b.dataset.remove!==undefined){mutate(()=>E.removePlan(state,Number(b.dataset.remove)));return;}
    if(b.dataset.choice!==undefined){if(mutate(()=>E.choose(state,Number(b.dataset.choice))))showEventResult();return;}
  });
  $('#modal').addEventListener('cancel',e=>{if($('#modal').dataset.resultOpen==='true')e.preventDefault();});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('#modal').open&&!['INPUT','TEXTAREA','BUTTON','SELECT'].includes(document.activeElement.tagName)&&state.phase==='planning'&&state.plan.length===3){e.preventDefault();commands.advance();}});
  $('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>300000)throw Error('存档文件过大，请选择本游戏导出的 JSON 文件');const raw=JSON.parse(await f.text());if(raw.format!=='CS-LIFE')throw Error('这不是本游戏的存档');const incoming=E.validate(raw.state);modal(`${modalTop('IMPORT SAVE / 导入存档')}<h2 id="modal-title">继续 ${esc(incoming.name)} 的故事？</h2><p class="modal-lead">第 ${incoming.semester} 学期，第 ${incoming.week} 周。<br>确认后将替换当前进度，已解锁成就保留。</p><div class="modal-bottom"><button class="quiet-btn" data-command="close">取消</button><button class="primary" id="confirm-import">确认导入</button></div>`);$('#confirm-import').addEventListener('click',()=>{state=incoming;save();close();render();showPhase();toast('存档已导入。');},{once:true});}catch(error){toast('导入失败：'+error.message);}});
  render();if(isNew)newGame();else showPhase();
  const context=document.modelContext;
  if(context?.registerTool){
    const lifecycle=new AbortController();
    const definitions=[{name:'read_student_life',description:'读取当前大学模拟进度、状态和可选行动，不改变游戏。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({name:state.name,semester:state.semester,week:state.week,phase:state.phase,health:state.health,mood:state.mood,gpa:E.gpa(state),plan:[...state.plan],actions:D.actions.map(a=>({id:a.id,name:a.name,locked:E.locked(state,a)}))})},{name:'set_week_plan',description:'替换当前周的行动计划，最多三项。只安排，不结算这一周。',inputSchema:{type:'object',properties:{actions:{type:'array',items:{type:'string'},maxItems:3}},required:['actions'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Array.isArray(input.actions)||input.actions.length>3||input.actions.some(id=>typeof id!=='string'))throw Error('提供最多三个行动 ID');if(state.phase!=='planning')throw Error('请先处理当前事件');const next=E.clone(state);next.plan=[];for(const id of input.actions)E.addPlan(next,id);state=next;save();render();return{plan:[...state.plan],executed:false};}}];
    for(const def of definitions){try{Promise.resolve(context.registerTool(def,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
